Defined usage optiones

diff --git a/lliurex-chboot.install/usr/sbin/chbootmgr b/lliurex-chboot.install/usr/sbin/chbootmgr
--- a/lliurex-chboot.install/usr/sbin/chbootmgr
+++ b/lliurex-chboot.install/usr/sbin/chbootmgr
@@ -17,12 +17,17 @@ BEGIN_SECTION="## BEGIN LLIUREX CHBOOT data ##"
 END_SECTION="## END LLIUREX CHBOOT data ##"
 CHBOOT_LABEL="chboot"
 CHBOOT_MOUNT="/chboot"
+CHBOOT_BASEDIR="$CHBOOT_MOUNT/lliurex-chboot"
 CHBOOT_FS="ext4"
-EFI_LLIUREX="lliurex-23"
+CHBOOT_TAG="/etc/lliurex-auto-upgrade/tags/chboot"
+EFI_LLIUREX="lliurex-25 lliurex-23"
 EFI_UBUNTU="ubuntu"
 EFI_MOUNT="/boot/efi"
 EFI_BASE="EFI"
-EFI_PREFIX="chbt_"
+EFI_PREFIX="chboot_"
+ISO_DIR="$CHBOOT_BASEDIR/isos"
+IMG_DIR="$CHBOOT_BASEDIR/imgs"
+CHBOOT_BOOTDIR="$CHBOOT_BASEDIR/boot"
 
 #############
 # functions #
@@ -44,7 +49,51 @@ die(){
 }
 
 usage(){
-	die "Usage:" "$(basename "$0") {grub-fix|grub-clean|status}"
+	die "Usage:" "$(basename "$0") {prepare|remove|mount|umount|boot-list|grub-fix|grub-clean|grub-status}" \
+	    "      $(basename "$0") enable CHBOOT_ENTRY" \
+	    "      $(basename "$0") bootnext CHBOOT_ENTRY" \
+	    "      $(basename "$0") boot [+SECONDS] CHBOOT_ENTRY"
+}
+
+main(){
+	[ "$1" ] || usage
+	ACTION="$1"
+	case "$ACTION" in
+		prepare)
+			if ! chboot_prepare ; then
+				chboot_remove
+				die "CHBOOT partition not found, aborting ..."
+			fi
+			;;
+		remove)
+			chboot_remove
+			;;
+		mount)
+			chboot_mount
+			;;
+		umount)
+			chboot_umount
+			;;
+		grub-fix)
+			grub_add_patch || die "EFI partition is not mounted, aborting ..."
+			;;
+		grub-clean)
+			grub_del_patch
+			;;
+		grub-status)
+			rc=0
+			grub_test_patch || rc=$?
+			if [ $rc -eq 0 ] ; then
+				echo "ON"
+			else
+				echo "OFF"
+			fi
+			exit $rc
+			;;
+		*)
+			usage
+			;;
+	esac
 }
 
 file_test_patch(){
@@ -60,18 +109,39 @@ file_del_patch(){
 	sed -i -e "/^${BEGIN_SECTION}$/,/^${END_SECTION}$/d" "$FILE"
 }
 
-chboot_init(){
-	chboot_get_uuid >/dev/null 2>/dev/null || return 1
-	chboot_add_fstab || return 1
-	chboot_mount || return 1
+
+chboot_prepare(){
+	if chboot_get_uuid >/dev/null 2>/dev/null ; then
+		chboot_tag_set
+		mkdir -p $CHBOOT_MOUNT
+#		chboot_add_mount || return 1
+#		chboot_mount || return 1
+		return 0
+	fi
+	return 1
 }
 
-chboot_clean(){
-	# do lazy umount 
-	umount -l $CHBOOT_MOUNT >/dev/null 2>/dev/null || true
-	chboot_del_fstab
+chboot_remove(){
+	chboot_umount
+	chboot_get_uuid >/dev/null 2>/dev/null || chboot_tag_unset
 	rmdir --ignore-fail-on-non-empty $CHBOOT_MOUNT >/dev/null 2>/dev/null || true
+	grub_del_patch
 }
+
+chboot_tag_set(){
+	touch "$CHBOOT_TAG"
+}
+
+chboot_tag_unset(){
+	rm -f "$CHBOOT_TAG"
+}
+
+chhboot_umount(){
+	# do lazy umount 
+	# umount -l $CHBOOT_MOUNT >/dev/null 2>/dev/null || true
+	systemctl stop chboot.mount
+}
+
 
 chboot_get_uuid(){
 	# chboot partition MUST HAVE chboot label
@@ -90,17 +160,6 @@ chboot_get_part(){
 	return 0
 }
 
-chboot_del_fstab(){
-	file_del_patch "$FSTAB_FILE"
-}
-
-chboot_test_fstab(){
-	if file_test_patch "$FSTAB_FILE" ; then
-		return 0
-	fi
-	return 1
-}
-
 chboot_test_mount(){
 	if df --output=target,source $CHBOOT_MOUNT |grep -q "^$CHBOOT_MOUNT" ; then
 		return 0
@@ -109,27 +168,11 @@ chboot_test_mount(){
 }
 
 chboot_mount(){
-	if ! chboot_test_mount ; then
-		mkdir -p $CHBOOT_MOUNT
-		mount $CHBOOT_MOUNT 2>/dev/null || true
-	fi
+	systemctl start chboot.mount
 	if chboot_test_mount ; then
 		return 0
 	fi
 	return 1
-}
-
-chboot_add_fstab(){
-	chboot_del_fstab
-	chboot_do_backup
-	CHBOOT_UUID="$(chboot_get_uuid)"
-	[ "$CHBOOT_UUID" ] || return 1
-	cat <<EOF >> "$FSTAB_FILE"
-$BEGIN_SECTION
-# mount chboot partition
-UUID=$CHBOOT_UUID	$CHBOOT_MOUNT	$CHBOOT_FS	defaults,noatime	0	1
-$END_SECTION
-EOF
 }
 
 entry_add(){
@@ -270,31 +313,6 @@ EOF
 	rm -f "$TMP_FILE"
 }
 
-main(){
-	[ "$1" ] || usage
-	ACTION="$1"
-	case "$ACTION" in
-		grub-fix)
-			grub_add_patch || die "EFI partition is not mounted, aborting ..."
-			;;
-		grub-clean)
-			grub_del_patch
-			;;
-		status)
-			rc=0
-			grub_test_patch || rc=$?
-			if [ $rc -eq 0 ] ; then
-				echo "ON"
-			else
-				echo "OFF"
-			fi
-			exit $rc
-			;;
-		*)
-			usage
-			;;
-	esac
-}
 
 ################
 # main program #
